In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [2]:
data = {
    'Age': [25,30,35,40,45,50,28,32,38,42],
    'Salary': [20000,25000,30000,35000,40000,45000,22000,27000,32000,37000],
    'Purchased': [0,0,1,1,1,1,0,0,1,1]
}

df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)

print("data.csv file created successfully!")
df

data.csv file created successfully!

   Age  Salary  Purchased
0   25   20000          0
1   30   25000          0
2   35   30000          1
3   40   35000          1
4   45   40000          1
5   50   45000          1
6   28   22000          0
7   32   27000          0
8   38   32000          1
9   42   37000          1

In [3]:
df = pd.read_csv('data.csv')
df.head()

   Age  Salary  Purchased
0   25   20000          0
1   30   25000          0
2   35   30000          1
3   40   35000          1
4   45   40000          1

In [4]:
X = df[['Age', 'Salary']]
y = df['Purchased']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (7, 2)
Testing Data: (3, 2)

In [6]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [7]:
y_pred = model.predict(X_test)

print("Predictions:", y_pred)

Predictions: [1 0 1]

In [8]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy of Naïve Bayes Classifier:", accuracy)

Accuracy of Naïve Bayes Classifier: 1.0

In [9]:
# Example test data
new_data = [[29, 26000]]

prediction = model.predict(new_data)

if prediction[0] == 1:
    print("Customer will Purchase")
else:
    print("Customer will NOT Purchase")

Customer will NOT Purchase

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(